// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

async function repl(CLIO, DL) {
  var cliInterface = Curry._3(CLIO.on, Curry._1(CLIO.make, undefined), "close", DL.cleanup);
  var close = function (param) {
    Curry._1(CLIO.close, cliInterface);
  };
  var prompt = async function (s) {
    return await Curry._3(CLIO.prompt, cliInterface, "\u03BB> ", Curry._1(DL.handleUserInput, s));
  };
  await Curry._2(DL.start_repl, prompt, close);
  return new Promise((function (resolve, _reject) {
                resolve(undefined);
              }));
}

exports.repl = repl;
/* No side effect */
