// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function repl(CLIO, DL) {
  var cliInterface = Curry._3(CLIO.on, Curry._1(CLIO.make, undefined), "close", DL.cleanup);
  var $$continue = {
    contents: false
  };
  while($$continue.contents) {
    Curry._3(CLIO.prompt, cliInterface, "\u03BB> ", DL.handleUserInput).then(function (cont_or_close) {
          return new Promise((function (resolve, _reject) {
                        if (cont_or_close) {
                          $$continue.contents = false;
                          return resolve(cont_or_close);
                        } else {
                          return resolve(cont_or_close);
                        }
                      }));
        });
  };
  console.log("See you Space Cowboy");
}

exports.repl = repl;
/* No side effect */
