// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

function intEqual(message, a, b) {
  Test.assertion(message, "Int equals", (function (a, b) {
          return a === b;
        }), a, b);
}

function equals(message, a, b) {
  Test.assertion(message, "equals", Caml_obj.equal, a, b);
}

exports.intEqual = intEqual;
exports.equals = equals;
/* Test Not a pure module */
