// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function id(x) {
  return x;
}

function pipe(g, f, x) {
  return Curry._1(f, Curry._1(g, x));
}

function compose(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

exports.id = id;
exports.pipe = pipe;
exports.compose = compose;
/* No side effect */
