// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Utils = require("../utils/Utils.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

function TestApplicative(A) {
  var test_id = function (x) {
    return Caml_obj.equal(Curry._2(A.apply, Curry._1(A.pure, Utils.id), x), x);
  };
  var test_hom = function (f, x) {
    return Caml_obj.equal(Curry._2(A.apply, Curry._1(A.pure, f), Curry._1(A.pure, x)), Curry._1(A.pure, Curry._1(f, x)));
  };
  var test_interchange = function (u, y) {
    return Caml_obj.equal(Curry._2(A.apply, u, Curry._1(A.pure, y)), Curry._2(A.apply, Curry._1(A.pure, (function (f) {
                          return Curry._1(f, y);
                        })), u));
  };
  var test_composition = function (u, v, w) {
    return Caml_obj.equal(Curry._2(A.apply, Curry._2(A.apply, Curry._2(A.apply, Curry._1(A.pure, Utils.compose), u), v), w), Curry._2(A.apply, u, Curry._2(A.apply, v, w)));
  };
  return {
          test_id: test_id,
          test_hom: test_hom,
          test_interchange: test_interchange,
          test_composition: test_composition
        };
}

exports.TestApplicative = TestApplicative;
/* No side effect */
