// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Utils = require("../utils/Utils.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

function TestFunctor(F) {
  var test_id = function (x) {
    return Caml_obj.equal(Curry._2(F.fmap, Utils.id, x), x);
  };
  var test_compose = function (x) {
    var f = function (x) {
      return x % 2;
    };
    var g = function (x) {
      return x - 1 | 0;
    };
    return Caml_obj.equal(Curry._2(F.fmap, (function (param) {
                      return Utils.pipe(g, f, param);
                    }), x), Curry._2(F.fmap, f, Curry._2(F.fmap, g, x)));
  };
  return {
          test_id: test_id,
          test_compose: test_compose
        };
}

exports.TestFunctor = TestFunctor;
/* No side effect */
