// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.bs.js");
var REPLLogic = require("../../src/repl-logic/REPLLogic.bs.js");
var TestUtils = require("../repl-commands-parser/test-utils/TestUtils.bs.js");

Test.test("Successfully parses the ':load' command", (function (param) {
        var result = REPLLogic.parseReplCommand(":load Utils");
        TestUtils.equals(undefined, {
              TAG: /* LoadModule */1,
              _0: "Utils"
            }, result);
      }));

Test.test("Successfully parses the ':{' (start multiline mode) command", (function (param) {
        var result = REPLLogic.parseReplCommand(":{");
        TestUtils.equals(undefined, /* StartMultiLineMode */0, result);
      }));

Test.test("Successfully parses the '}:' (end multiline mode) command", (function (param) {
        var result = REPLLogic.parseReplCommand("}:");
        TestUtils.equals(undefined, /* EndMultiLineMode */1, result);
      }));

Test.test("All other string input yields the RescriptCode command", (function (param) {
        var result = REPLLogic.parseReplCommand("some user input that won't compile");
        TestUtils.equals(undefined, {
              TAG: /* RescriptCode */0,
              _0: "some user input that won't compile"
            }, result);
      }));

/*  Not a pure module */
